
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_management
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql:true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    
server:
  port: 8085
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
  info:
    env:
      enabled: true
        
info:
  app:
    name: Spring Boot restful web services
    description: Spring Boot resful Web Services Demo
    version: 1.0.0