spring:
  application:
    name: DEPARTMENT-SERVICE
  config:
    import: optional:configserver:http://localhost:8888


#server:
#  port: 8081
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/department_db
#    username: postgres
#    password: password
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql:true
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#

#eureka:
#  instance:
#    client:
#      serverUrl:
#        defaultZone: http://localhost:8761/eureka