#server:
#  port: 8082
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/employee_db
#    username: postgres
#    password: password
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql:true
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    
#
spring:
  application:
    name: EMPLOYEE-SERVICE
  config:
    import: optional:configserver:http://localhost:8888

#Actuator endpoints
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - health 
    health:
      show-details: always    
      
#Circuit Breaker configuration
resilience4j:
  circuitbreaker:
    instances:
      EMPLOYEE-SERVICE:
        register-health-indicator: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
         
#eureka:
#  instance:
#    client:
#      serverUrl:
#        defaultZone: http://localhost:8761/eureka