server:
  port: 8888

spring:
  application:
    name: CONFIG-SERVER
  
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Intekhab-1761/Config-Server-Repo
          clone-on-start: true
          default-label: main

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka